image: node:latest
services:
   - docker:latest

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --tag awesome-devops-and-cd .
    - docker save -o ${CI_COMMIT_SHA}.tar awesome-devops-and-cd
  artifacts:
    paths:
      - ${CI_COMMIT_SHA}.tar
    expire_in: 1 week

deploy:
  stage: deploy
  image: williamyeh/ansible:ubuntu:18.04
  script:
    - ansible-playbook --extra-vars="github_commit=${CI_COMMIT_SHA} ansible_user=${SSH_USER} ansible_password=${SSH_PASSWORD}" -i env/production deploy.yml
