image: node:latest
services:
   - docker:latest

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --tag awesome-devops-and-cd .
    - docker save -o ${CI_COMMIT_SHA}.tar awesome-devops-and-cd

deploy:
  stage: deploy
  script:
    - echo "qui va chiamato lo script ansible"
